# Site settings
# in the templates available like {{ site.myvariable }}.
title: More learn more lucky.
email: zhang_xianfa@tom.com
brand: Xianfa
headline: It's never too late to start
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xianfa.github.io/" # the base hostname & protocol for your site
copyright: All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: zhang_xianfa@tom.com
phone: 13588888888

# Tracking
googleAnalitycsID: UA-83933844-1

